version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: urpagin-dot-net
    ports:
      - "51494:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    depends_on:
      - caddy
    restart: always

  caddy:
    image: caddy:latest
    container_name: urpagin-dot-net-webhook-listener
    ports:
      - "42047:9000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - .:/website
    environment:
      - GIT_REPO=https://github.com/Urpagin/urpagin-dot-net.git
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    command: >
      sh -c "
      if [ ! -d /website/.git ]; then
        git clone $GIT_REPO /website;
      else
        git -C /website pull;
      fi &&
      docker compose -f /website/docker-compose.yml pull &&
      docker compose -f /website/docker-compose.yml up -d &&
      caddy run --config /etc/caddy/Caddyfile"
    restart: always
